### PR TITLE
Improve build.py

### PR DESCRIPTION
**Pull request by crisisinaptica**
· Formated code to adhere to PEP8 style guide

· 'input', 'vars', and 'type' variables/arguments renamed, since these
are python built-in function names and should't be used for other
purposes

· Fix bug in main(): If 'dist' dir doesn't exist create it before trying
to write files to it

### CODE REVIEW

**Comment by Korshun** [comment]
Thanks, but you should be aware that build.py is just a quick unoptimized hack.

**Comment by crisisinaptica** [comment]
Sorry, didn't know.
I would like to write a PKGBUILD for the Arch Linux AUR, to build the libraries and package them directly from the last git commit.
What's the alternative to build.py?

Do you want me to close this PR?

Thanks!

**Comment by Korshun** [comment]
No, thanks for improvements that I was too lazy to do myself.

But why do you want ACSUtils as a linux package? build.py is used to make releases of ACSUtils. The released versions of ACSUtils are meant to be copied to mods. Each release is accompanied by a changelog and a list of backwads incompatibilities.

**Comment by crisisinaptica** [comment]
Yeah, I went ahead of myself, it really don't make sense to make an acsutils package.
I'm just learning now all thing related to Doom modding.
: /

EDIT: 
Would it make sense to install acsutils as a package and include the library via the acc '-i' command line option?

**Comment by Korshun** [comment]
Maybe it would, but the recommended way to use ACSUtils is to copy it to your mod, because it makes it easy to recompile the mod without downloading anything and prevents compiling the mod's ACS with an incorrect version of ACSUtils. Also, ACSUtils has some decorate and cvarinfo files that are not part of the ACS and MUST be copied to the mod, as they cannot be included from outside.

**Comment by crisisinaptica** [comment]
Thanks for the clarifications.

**Pull request merged**
